# Dependencies
markdown:         kramdown
highlighter:      pygments

# Setup
title:            'Robert Farmer'
tagline:          ' '
description:      ' '
url:              https://github.com/rjfarmer
baseurl:          /
images:           assets

author:
  name:           'Robert Farmer'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rjfarmer
