header:
    title: 
    text: Rob Farmer's science
    button: To Science!
    buttonlink: "#services"

services:
    title: "Research Interests"
    text: ""
    section: services
    list:
      - title: "Massive stars"
        desc: ""
        icon: assets/img/bonanza-0.png
      - title: "Stellar evolution"
        desc: ""
        icon: assets/img/mesa.png    
      - title: "Gravitational Waves"
        desc: ""
        icon: assets/img/bhbh.png 
      - title: "Binary Stars"
        desc: ""
        icon: assets/img/binary.png
      - title: "Population Synthesis"
        desc: ""
        icon: assets/img/random.png

portfolio:
    title: "Recent work"
    text: ""
    section: portfolio
    closebutton: "Close Project"
    

timeline:
    title: "C.V" 
    text: 
    section: 
    cvfile: assets/cv.pdf
    # left is the default
    #start_align: "left"
    events:
      - title: "Post-Doc University Of Amsterdam"
        year: "2017-"
        desc: "In this post doc I am currently trying to understand what we can learn about the lives and deaths of massive stars from merging binary black holes detected by LIGO/Virgo. I continue to work on developing the MESA stellar evolution code "
        image: assets/img/api.png
        align: bottom
      - title: "Post-Doc Arizona State University"
        year: "2014-2017"
        desc: "My first post doc focused on understanding how massive stars that will explode live and die. This include SAGB stars and core collapse progenitors. The other part of my time was spent developing the MESA stellar evolution code."
        image: assets/img/asu_logo.png
        align: bottom
      - title: "PhD The Open University"
        year: "2010-2014"
        desc: "My PhD focused on understanding the stars that made up the Kepler field of view. I was particularly interested in understanding the effect of binarity on how Kepler selected its targets."
        image: assets/img/OU-logo.png
        align: bottom
      - title: "MPhys Warwick University"
        year: "2006-2010"
        desc: ""
        image: assets/img/warwick.jpeg
        align: bottom
   # end: ""

team:
    title: "Links"
    text: ""
    subtext: 
    section: team
    people:
      - name: "Github"
        role: "[https://github.com/rjfarmer](https://github.com/rjfarmer)"
        image: assets/img/github.jpeg
      - name: "ADSABS"
        image: assets/img/adsabs.svg
        role: "[ADSABS](https://ui.adsabs.harvard.edu/search/q=orcid%3A0000-0003-3441-7624&sort=date%20desc%2C%20bibcode%20desc&p_=0)"
      - name: "ORCID"
        image: assets/img/768px-ORCID_iD.svg.png
        role: "[Orcid](https://orcid.org/0000-0003-3441-7624)"
          
# contact:
#     title: "Contact Us"
#     text: "Lorem ipsum or call 123456789"
#     section: contact
    
footer:
    legal: "Privacy Policy"
    # social:
    #   - url: https://twitter.com
    #     icon: "fab fa-twitter"  
    #   - url: https://facebook.com
    #     icon: "fab fa-facebook-f"
    #   - url: https://linkedin.com
    #     icon: "fab fa-linkedin-in"
    #   - url: https://github.com/raviriley/agency-jekyll-theme
    #     icon: "fab fa-github"
    #   - url: https://instagram.com
    #     icon: "fab fa-instagram"


# {{ site.data.sitetext.ex.ex | markdownify | default: example }}
